### ISSUE TITLE
Issues when running in a closed environment

### ISSUE THREAD

**Issue by Pavansid94** [sashirestela/simple-openai#153]
Forgive my naivete. I have just started using this API via a maven dependency. The documentation is well made and clearly understandable. But i get the following exception as soon as i make 'Chat completion' request. Do you have an idea as to what maybe causing this issue?

![image](https://github.com/sashirestela/simple-openai/assets/56548270/839e6ac7-9958-40ed-acbd-4d591f7de550)

Now, i don't see how this trivial error seems to happen, but it seems to point to the class 'ConstraintViolationException' which ofcourse i can't find in my classpath too, but the dependency seems to be onboarded as expected. I just hope that the above attachement is intuitive enough, let me know if you need more info. Thanks in advance.

**Comment by sashirestela** [comment]
Hi @Pavansid94, thanks for using simple-openai.

It's a weird issue. I don't think that you are excluding the [slimvalidator](https://github.com/sashirestela/cleverclient) library from your pom.xml, do you? I'd suggest clearing your local repository: Sometimes clearing the local repository and forcing Maven to re-download dependencies can resolve issues with corrupt artifacts. You can do this by deleting the specific folders in `~/.m2/repository`

**Comment by Pavansid94** [comment]
Okay, a bit more progress from my side, As it turns out, the slimValidator (as you rightly pointed out) was missing from the classpath. And i was able to rectify this issue and i'm currently tring to make a 'Chat completion' request. However, i get the following exception:

![image](https://github.com/sashirestela/simple-openai/assets/56548270/8df2d629-9ced-4535-bc6f-19e69f1ccca3)

I'm running my application currently locally and have no ssl certificate configured, could it be because of this? would i need it?

**Comment by sashirestela** [comment]
No, simple-openai doesn't need it, nor its dependencies. From your first image, I can see that you are working with the Spring framework, maybe there is something there.

On the other hand, I recommend you to attach the entire log file to see more details.

**Comment by sashirestela** [comment]
@Pavansid94 Do you have any news here? Let me know if I can close this issue.

**Comment by Pavansid94** [comment]
Hi @sashirestela , i'm sorry that it took a bit of time to get back to you. Basically, i've been held back by my other commitments and therefore have not been able to make much progress. However, i can give you more info on what i've done so far.

So due to a few reasons i'm not able to add your library as an external dependancy to my codebase (the dependancy never gets resolved, this might be because that my maven is not able to find 'simple-openai' through the current indexed repos that i have). But , ive added them currently as external Jars and they seem to work okay, unless of course, when i eventually do a  'Chat completion' request.  And yes, as you correctly surmised, i'm using this as part of my Spring-based Web app to see whether i'll get somewhere. I'm not an SSH/SSl expert whatsoever, but i know i can sign a self-signed certificate to get it going, but i've not gone ahead and done it yet.

additionally, i can of course attach the entire stacktrace (as follows), of course, maybe you can give me some ideas :)


```
2024-06-18T09:04:27.202+02:00  INFO 30580 --- [           main] c.a.h.O.OpenWebUIConnectorApplication    : Starting OpenWebUIConnectorApplication using Java 17.0.11 with PID 30580 
2024-06-18T09:04:27.205+02:00  INFO 30580 --- [           main] c.a.h.O.OpenWebUIConnectorApplication    : No active profile set, falling back to 1 default profile: "default"
2024-06-18T09:04:28.221+02:00  INFO 30580 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-06-18T09:04:28.234+02:00  INFO 30580 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-06-18T09:04:28.234+02:00  INFO 30580 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.24]
2024-06-18T09:04:28.300+02:00  INFO 30580 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-06-18T09:04:28.301+02:00  INFO 30580 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1046 ms
2024-06-18T09:04:28.649+02:00  INFO 30580 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2024-06-18T09:04:28.656+02:00  INFO 30580 --- [           main] c.a.h.O.OpenWebUIConnectorApplication    : Started OpenWebUIConnectorApplication in 1.828 seconds (process running for 2.177)
2024-06-18T09:04:37.326+02:00  INFO 30580 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-06-18T09:04:37.326+02:00  INFO 30580 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-06-18T09:04:37.327+02:00  INFO 30580 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-06-18T09:04:37.959+02:00 ERROR 30580 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.util.concurrent.CompletionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] with root cause

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[na:na]
	at java.base/sun.security.validator.Validator.validate(Validator.java:264) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209) ~[na:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1118) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(SSLFlowDelegate.java:1113) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1079) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:484) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(SequentialScheduler.java:347) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:151) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

Maybe, an additonal info might be that i'm currently trying to connect to an instance of 'Open-AI' hosted into our organisation's servers and therefore have the corresponding 'API-Key' that are valid to only this instance (But again, this shouldn't be a problem as your API fully supports it too ).

Anyway, i appreciate your support and apologise fully, to my delayed answer. Thanks :)

**Comment by sashirestela** [comment]
@Pavansid94 To be honest, it is complicated trying to provide any help or suggestions if you are working in a closed environment. As far as I've seen the issues are related to your environment and not to simple-openai directly. Then, I think this issue should be closed. If you have any questions, I suggest using the [Discussion](https://github.com/sashirestela/simple-openai/discussions) section.

**Comment by didalgolab** [comment]
@Pavansid94 The error "unable to find valid certification path to requested target" indicates that Java doesn't trust the certificate your server uses when establishing a connection. You mentioned connecting to an "Open-AI" instance hosted on your organization's servers. Check if your "Open-AI" servers use self-signed or otherwise unrecognized certificates. If so, import the certificates into Java's keystore. These links may help you move forward:
- https://stackoverflow.com/questions/63482370/unable-to-find-a-valid-certification-path-to-requested-target
- https://stackoverflow.com/questions/9210514/unable-to-find-valid-certification-path-to-requested-target-error-even-after-c

**Comment by Pavansid94** [comment]
Hi @didalgolab, Thanks for answering, appreciate it. Let me have a look.
