### ISSUE TITLE
Chat Completion with streaming example

### ISSUE THREAD

**Issue by emre010101** [sashirestela/simple-openai#154]
Hello there, I copied your example for chat streaming however faced this index problem.  Why this could be happening?

Thank you :)

        var futureChat = openAI.chatCompletions().createStream(chatRequest);
        var chatResponse = futureChat.join();
        chatResponse.filter(chatResp -> chatResp.firstContent() != null)
                .map(Chat::firstContent)
                .forEach(System.out::print);

ChatGPT is an advanced language model developed by OpenAI, designed to generate human-like responses in conversational settings. Leveraging the power of the GPT-3 architecture, ChatGPT can understand and respond to a wide range of prompts, making it suitable for chatbots, virtual assistants, and other natural language processing applications. With its ability to understand context, generate coherent responses, and exhibit a high degree of linguistic fluency, ChatGPT represents a significant advancement in AI-driven conversational agents. Its potential applications span across customer service, education, entertainment, and more, making it a versatile and powerful tool in the realm of artificial intelligence.Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at io.github.sashirestela.openai.domain.chat.Chat.firstMessage(Chat.java:30)
	at io.github.sashirestela.openai.domain.chat.Chat.firstContent(Chat.java:34)
	at ie.ncirl.esta.service.impl.LlmServiceImpl.lambda$main$12(LlmServiceImpl.java:156)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at ie.ncirl.esta.service.impl.LlmServiceImpl.main(LlmServiceImpl.java:158)

**Comment by sashirestela** [comment]
Hi @emre010101, thanks for using simple-openai!

Sorry for being delayed here, I was busy with my full time job. The issue here is that the Readme needs to be updated, my bad. If you want to run the Chat Streaming example, please take the following blocks of code as a reference:

https://github.com/sashirestela/simple-openai/blob/main/src/demo/java/io/github/sashirestela/openai/demo/ChatDemo.java#L41-L45

https://github.com/sashirestela/simple-openai/blob/main/src/demo/java/io/github/sashirestela/openai/demo/ChatDemo.java#L144-L157

In general, it is better to see the code in the [demo](https://github.com/sashirestela/simple-openai/tree/main/src/demo/java/io/github/sashirestela/openai/demo) folder.

Let me know if it works for you.

**Comment by emre010101** [comment]
Hey @sashirestela,
Thank you for your quick response and providing this brilliant library.
It worked with example.
Basically when streaming, the last message which only consist of the usage and there are no choices, processing the chunk with checking only the choices if it's empty you bypass the null pointer exception.

**Comment by sashirestela** [comment]
@emre010101 If you find this project valuable there are a few ways you can show us your love, preferably all of them 🙂:

- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.

**Comment by sashirestela** [comment]
@emre010101 I've just updated the Readme with functional examples. Thanks.

**Comment by emre010101** [comment]
@sashirestela thank you. It would be better for new joiners to library.
