### ISSUE TITLE
FunctionExecutor fails when ChatGPT returns "" as function call parameters.

### ISSUE THREAD

**Issue by onhachoe** [sashirestela/simple-openai#167]
ChatGPT occasionally returns empty string as function call arguments parameter when function does not have any arguments.

e.g.
```
{
  "role": "assistant",
  "tool_calls": [
    {
      "id": "some_id",
      "type": "function",
      "function": {
        "name": "some_function",
        "arguments": ""
      }
    }
  ]
}      
```

and FunctionExecutor throws with
```
Caused by: io.github.sashirestela.cleverclient.support.CleverClientException: Cannot convert the Json  to class com.invisible.framework.hmaa.web.automation.instruction.ExecuteWithoutInstructionTool.
	at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:48)
	at io.github.sashirestela.openai.common.function.FunctionExecutor.execute(FunctionExecutor.java:81)
	... 42 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2115)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1586)
	at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:46)
	... 43 more
```

This is probably a bad response from OpenAI, but would be nice we can gracefully handle this case.

**Comment by onhachoe** [comment]
Create PR #166 to fix the issue.

**Comment by sashirestela** [comment]
@onhachoe Thanks for using simple-openai! Could you share your function definition including description, please? As far as I know, you could use the description to ask the LLM to respond in a specific way/pattern.

**Comment by onhachoe** [comment]
For IP reasons, I cannot share the exact function definition. but the gist is
```
  {
    "type": "function",
    "function": {
      "name": "execute_something",
      "description": "Execute something to achieve the goal.",
      "parameters": {
        "type": "object",
        "properties": {}
      }
    }
  }
```

Most of the time, gpt correctly responds with arguments parameter set as "{}", but for about one out of 200 times, it will give empty string as its arguments to function call.
Given empty string is a never valid response, swapping it with "{}" seems valid.
