### ISSUE TITLE
io.github.sashirestela.cleverclient.support.CleverClientException: Cannot convert the Json

### ISSUE THREAD

**Issue by amavashev** [sashirestela/simple-openai#186]
io.github.sashirestela.cleverclient.support.CleverClientException: Cannot convert the Json {"error":{"message":"The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID req_070d9fdc6541acfe4ac7f1f6e5490a8e in your email.)","type":"server_error","param":null,"code":null}} to class java.lang.String.
        at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:48)
        at io.github.sashirestela.cleverclient.sender.HttpAsyncStreamEventSender.lambda$sendRequest$1(HttpAsyncStreamEventSender.java:37)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at ai.persona.services.openai.OpenaiCommunicationService.handleRunEvents(OpenaiCommunicationService.java:260)
        at ai.persona.services.openai.OpenaiCommunicationService.runConversation(OpenaiCommunicationService.java:209)
        at ai.persona.services.ContextRequestsHandleService.processRequest(ContextRequestsHandleService.java:72)
        at ai.persona.services.events.ContextRequestEventsAsyncListener.handleContextRequestEvent(ContextRequestEventsAsyncListener.java:24)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1446)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:958)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1441)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:48)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1586)
        at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:46)
        ... 27 common frames omitted

**Comment by sashirestela** [comment]
@amavashev Could you share your request?

On the other hand, it looks like an issue from OpenAI:

https://community.openai.com/t/500-the-server-had-an-error-processing-your-request-sorry-about-that-you-can-retry-your-request-or-contact-us-through-our-help-center-at-help-openai-com-if-you-keep-seeing-this-error/929933

**Comment by amavashev** [comment]
Dont have original request, but its a standard Assistant call with a prompt.

**Comment by sashirestela** [comment]
> Dont have original request, but its a standard Assistant call with a prompt.

It should be a random error from OpenAI. I've just run the `ConversationV2` demo code and the assistant works fine.

**Comment by sashirestela** [comment]
@amavashev What model version are you using? Maybe you could change to the latest one?

**Comment by amavashev** [comment]
gpt4o-mini
