### ISSUE TITLE
 JSON Decode Error When Using AzureOpenAI with This Repository

### ISSUE THREAD

**Issue by matsumoto-hisa** [sashirestela/simple-openai#187]
Hello,

I hope this message finds you well. I am encountering an error while trying to utilize AzureOpenAI with the code from this repository. I would greatly appreciate your guidance on identifying the cause and potential solutions for this issue.

### Version
io.github.sashirestela:simple-openai:3.8.0

### Error Details

```
2024-09-05 11:32:57.017+0900 [ForkJoinPool.commonPool-worker-1] ERROR io.github.sashirestela.cleverclient.sender.HttpSender - Response : {
  "error": {
    "message": "[{'type': 'json_invalid', 'loc': ('body', 47), 'msg': 'JSON decode error', 'input': {}, 'ctx': {'error': \"Expecting ',' delimiter\"}}]",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
Exception in thread "main" java.util.concurrent.CompletionException: io.github.sashirestela.cleverclient.support.CleverClientException: ERROR : {
  "error": {
    "message": "[{'type': 'json_invalid', 'loc': ('body', 47), 'msg': 'JSON decode error', 'input': {}, 'ctx': {'error': \"Expecting ',' delimiter\"}}]",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.github.sashirestela.cleverclient.support.CleverClientException: ERROR : {
  "error": {
    "message": "[{'type': 'json_invalid', 'loc': ('body', 47), 'msg': 'JSON decode error', 'input': {}, 'ctx': {'error': \"Expecting ',' delimiter\"}}]",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
        at io.github.sashirestela.cleverclient.sender.HttpSender.throwExceptionIfErrorIsPresent(HttpSender.java:62)
        at io.github.sashirestela.cleverclient.sender.HttpAsyncCustomSender.lambda$sendRequest$0(HttpAsyncCustomSender.java:19)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 9 more
```

### Implementation Details

I implemented the source code by referring to `ChatAzureDemo` as follows:

```java
import io.github.sashirestela.openai.SimpleOpenAIAzure;
import io.github.sashirestela.openai.domain.chat.ChatMessage.SystemMessage;
import io.github.sashirestela.openai.domain.chat.ChatMessage.UserMessage;
import io.github.sashirestela.openai.domain.chat.ChatRequest;

public class App {
    public static void main(String[] args) {
        var openai = SimpleOpenAIAzure.builder()
                .apiKey(System.getenv("AZURE_OPENAI_API_KEY"))
                .baseUrl(System.getenv("AZURE_OPENAI_BASE_URL"))
                .apiVersion(System.getenv("AZURE_OPENAI_API_VERSION"))
                .build();
        ChatRequest chatRequest = ChatRequest.builder()
                .model("N/A")
                .message(SystemMessage.of("You are an expert in AI."))
                .message(UserMessage.of("Write a technical article about ChatGPT, no more than 100 words."))
                .temperature(0.0)
                .maxTokens(300)
                .build();
        var futureChat = openai.chatCompletions().create(chatRequest);
        var chatResponse = futureChat.join();
        System.out.println(chatResponse.firstContent());
    }
}
```

I would be grateful if you could review this issue and provide any insights or suggestions. Thank you for your time and assistance.

Best regards,

**Comment by sashirestela** [comment]
@the-gigi would you mind taking a look at this issue, please?

**Comment by sashirestela** [comment]
@matsumoto-hisa What specific Azure OpenAI model are you using for this?

**Comment by surki01** [comment]
Hello,

I am also facing this isue. After debugging further, I have found that the implementation in the below method assumes that the "model" field in the JSON will always be at the start position. 

https://github.com/sashirestela/simple-openai/blob/77f5100016b2117a7a8a633c2397476c10a84e2e/src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java#L66

This assumption works fine for "assistants" API as the "AssistantRequest" class has "model" field as the first attribute, hence it gets added at the start position in the request JSON body.

But, the "ChatRequest" class has "model" field as the second attribute, causing it to be added at the second position that causes the logic in the aforemntioned class to incorrectly replace the model string in the JSON.

**Proposed Solution:** One option is to specify the order of the fields in JSON, but I would recommend to fix the pattern matching and replacing logic insulated from the order of the fields in the JSON.

**Comment by sashirestela** [comment]
@matsumoto-hisa @surki01 Thanks for your contribution with this issue. The fix is already available in the new 3.8.1 minor release.

**Comment by surki01** [comment]
@sashirestela Thanks for fixing this. I will try with the latest version and let you know of any issues.

**Comment by sashirestela** [comment]
@matsumoto-hisa @surki01 If you find this project valuable, there are a few ways you can show us your love, preferably all of them 🙂:

- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.

Thanks in advance!

**Comment by matsumoto-hisa** [comment]
@sashirestela Thanks!!
