### ISSUE TITLE
Missing value `incomplete` for ThreadRun.status field

### ISSUE THREAD

**Issue by amavashev** [sashirestela/simple-openai#210]
Caused by: io.github.sashirestela.cleverclient.support.CleverClientException: Cannot convert the Json {
  "id": "run_hHpEjbv2KvZX0D63QZW8MRDi",
  "object": "thread.run",
  "created_at": 1731727561,
  "assistant_id": "asst_Tx6mXCKXqI3en8fvYsLlQULc",
  "thread_id": "thread_TRxM82cnkJWfq2firwwGTYBx",
  "status": "incomplete",
  "started_at": 1731727577,
  "expires_at": null,
  "cancelled_at": null,
  "failed_at": null,
  "completed_at": 1731727588,
  "required_action": null,
  "last_error": null,
  "model": "gpt-4o-mini",
  "instructions": "a dental doctor Your name is Taranom_aibot",
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "generate_image",
        "description": "If a user requests to generate an image in any way. Ask for prompt if not provided before execution.",
        "parameters": {
          "type": "object",
          "properties": {
            "engine": {
              "type": "string",
              "description": "If engine is provided then use it. e.g. stability, dalle, grok"
            },
            "prompt": {
              "type": "string",
              "description": "Get the description of the image that should be generated"
            }
          },
          "required": [
            "prompt"
          ],
          "additionalProperties": false
        },
        "strict": false
      }
    },
    {
      "type": "file_search",
      "file_search": {
        "ranking_options": {
          "ranker": "default_2024_08_21",
          "score_threshold": 0.0
        }
      }
    }
  ],
  "tool_resources": {},
  "metadata": {},
  "temperature": 1.0,
  "top_p": 1.0,
  "max_completion_tokens": 4000,
  "max_prompt_tokens": 30000,
  "truncation_strategy": {
    "type": "auto",
    "last_messages": null
  },
  "incomplete_details": {
    "reason": "max_prompt_tokens"
  },
  "usage": {
    "prompt_tokens": 181689,
    "completion_tokens": 299,
    "total_tokens": 181988,
    "prompt_token_details": {
      "cached_tokens": 0
    }
  },
  "response_format": "auto",
  "tool_choice": "auto",
  "parallel_tool_calls": true

} to class io.github.sashirestela.openai.domain.assistant.ThreadRun.
        at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:48)
        at io.github.sashirestela.cleverclient.sender.HttpAsyncCustomSender.lambda$sendRequest$0(HttpAsyncCustomSender.java:23)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 5 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `io.github.sashirestela.openai.domain.assistant.ThreadRun$RunStatus` from String "incomplete": not one of the values accepted for Enum class: [cancelling, cancelled, queued, expired, in_progress, completed, failed, requires_action]
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 7, column: 13] (through reference chain: io.github.sashirestela.openai.domain.assistant.ThreadRun["status"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1958)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1245)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:447)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:304)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:273)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1586)
        at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:46)
        ... 7 common frames omitted

**Comment by amavashev** [comment]
Seems like run status "incomplete" is not being handled. https://platform.openai.com/docs/api-reference/runs/object#runs/object-status

**Comment by sashirestela** [comment]
> doesn't the state need to be added to AssistantStreamEvent.java?
> @StreamType(type = ThreadRun.class, events = { THREAD_RUN_CREATED, THREAD_RUN_QUEUED, THREAD_RUN_IN_PROGRESS,
>         THREAD_RUN_REQUIRES_ACTION, THREAD_RUN_COMPLETED, THREAD_RUN_FAILED, THREAD_RUN_CANCELLING,
>         THREAD_RUN_REQUIRES_ACTION, THREAD_RUN_COMPLETED, THREAD_RUN_INCOMPLETE, THREAD_RUN_FAILED, THREAD_RUN_CANCELLING,
>         THREAD_RUN_CANCELLED, THREAD_RUN_EXPIRED })
> 
> and EventName.java.
> public static final String THREAD_RUN_INCOMPLETE = "thread.run.incomplete";
> 

_Originally posted by @amavashev in https://github.com/sashirestela/simple-openai/pull/211#pullrequestreview-2440830827_

**Comment by sashirestela** [comment]
The fix has been deployed as part of the release 3.9.1
