### ISSUE TITLE
can not use. compeletion with image

### ISSUE THREAD

**Issue by fanmeijian** [sashirestela/simple-openai#33]
List<ContentPart> contentParts = new ArrayList<>();
		ContentPartText contentPartText = new ContentPartText(userMessageString);
		ContentPartImage contentPartImage = new ContentPartImage(new ImageUrl(imageBase64String));
		
		contentParts.add(contentPartText);
		contentParts.add(contentPartImage);
		chatMsgs.addAll(List.of(new ChatMsgSystem(conversation.getSystem()), new ChatMsgUser(contentParts)));
var chatRequest = ChatRequest.builder().stream(true).model(conversation.getModel()).messages(chatMsgs)
				.temperature(0.0).build();
		var futureChat = openai.chatCompletions().createStream(chatRequest);
		var chatResponse = futureChat.join();
		chatMsg.setConversationId(conversationId);
		ChatMsg savedChatMsg = this.chatMsgRepository.save(chatMsg);

		List<String> assistant1 = new ArrayList<>();
		return Flux.fromStream(chatResponse.map((m) -> {
			String s = m.firstContent();
			if (s != null) {
				assistant1.add(s);
//				assistant = String.join(assistant, s);
				return s;
			} else {
				return "";
			}
		})).doOnComplete(() -> {
			savedChatMsg.setAssistant(String.join("", assistant1));
			this.chatMsgRepository.save(savedChatMsg);
			System.out.println("last save" + savedChatMsg.getAssistant());

		});

when I make request, it fail with errors below, is there any example with how to use image in chat completion?

2024-01-05 17:29:25.755[0;39m [31mERROR[0;39m [35m69347[0;39m [2m---[0;39m [2m[onPool-worker-3][0;39m [36mi.g.s.cleverclient.sender.HttpSender    [0;39m [2m:[0;39m Response : {
  "error": {
    "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
[2m2024-01-05 17:29:25.769[0;39m [31mERROR[0;39m [35m69347[0;39m [2m---[0;39m [2m[nio-8880-exec-6][0;39m [36mo.a.c.c.C.[.[.[.[dispatcherServlet]     [0;39m [2m:[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [/gpt-service] threw exception [Request processing failed; nested exception is java.util.concurrent.CompletionException: io.github.sashirestela.cleverclient.support.CleverClientException: ERROR : {
  "error": {
    "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}] with root cause

io.github.sashirestela.cleverclient.support.CleverClientException: ERROR : {
  "error": {
    "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
	at io.github.sashirestela.cleverclient.sender.HttpSender.throwExceptionIfErrorIsPresent(HttpSender.java:43) ~[cleverclient-0.10.0.jar:na]
	at io.github.sashirestela.cleverclient.sender.HttpAsyncStreamSender.lambda$sendRequest$2(HttpAsyncStreamSender.java:21) ~[cleverclient-0.10.0.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

**Comment by sashirestela** [comment]
@fanmeijian Thanks for using simple-openai. I'm preparing the fix for the issue.

**Comment by sashirestela** [comment]
@fanmeijian The fix has been included in the last release 1.2.5

**Comment by fanmeijian** [comment]
> @fanmeijian The fix has been included in the last release 1.2.5

Hi Sashirestela, let me try, thanks!

**Comment by sashirestela** [comment]
@fanmeijian Thanks for using simple-openai. If you find this project valuable there are a few ways you can show us your love:

- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.
