### ISSUE TITLE
Error with ThreadRunStepDelta

### ISSUE THREAD

**Issue by Mojo774** [sashirestela/simple-openai#70]
"2024-03-30T12:45:07.010+08:00 ERROR 24570 --- [nio-8080-exec-6] c.e.m.l.contrlollers.AdviceController    : Cannot convert the Json {"id":"step_vudsWHBvG20b7CEfQBXsfK8W","object":"thread.run.step.delta","delta":{"step_details":{"type":"tool_calls","tool_calls":[{"index":0,"id":"call_8C4mCMu5TEr2HnNmHo3duu8c","type":"function","function":{"name":"getCurrentWeather","arguments":"","output":null}}]}}} to class io.github.sashirestela.openai.domain.assistant.ThreadRunStepDelta.

io.github.sashirestela.cleverclient.support.CleverClientException: Cannot convert the Json {"id":"step_vudsWHBvG20b7CEfQBXsfK8W","object":"thread.run.step.delta","delta":{"step_details":{"type":"tool_calls","tool_calls":[{"index":0,"id":"call_8C4mCMu5TEr2HnNmHo3duu8c","type":"function","function":{"name":"getCurrentWeather","arguments":"","output":null}}]}}} to class io.github.sashirestela.openai.domain.assistant.ThreadRunStepDelta.
	at io.github.sashirestela.cleverclient.util.JsonUtil.jsonToObject(JsonUtil.java:48) ~[cleverclient-1.3.3.jar:na]
	at io.github.sashirestela.cleverclient.sender.HttpAsyncStreamEventSender.lambda$sendRequest$1(HttpAsyncStreamEventSender.java:37) ~[cleverclient-1.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.example.monolithapi.messaging.ai.services.GptAssistantService.runThread(GptAssistantService.java:126) ~[main/:na]
	at com.example.monolithapi.messaging.ai.services.GptAssistantService.testChat(GptAssistantService.java:80) ~[main/:na]
	at com.example.monolithapi.messaging.ai.controllers.AiController.createThreadWithMessage(AiController.java:65) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.10.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.10.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-6.0.10.jar:6.0.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar:10.1.10]
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.1.jar:6.1.1]
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.1.1.jar:6.1.1]"
	
Using @JsonTypeInfo and @JsonSubTypes:
In your class, the @JsonTypeInfo annotation is used to indicate that the deserialization of the StepDetails interface should be based on the value of the type field. Ensure that the JSON contains the appropriate value in the type field ("tool_calls" in your case) and that this value exactly matches one of the values specified in @JsonSubTypes.Type.

ToolCall class:
The index field in the ToolCall class is declared as a String, while in your JSON, it appears as a numeric value ("index":0). Ensure that the data type of the index field matches the data format in JSON. If the index is supposed to be a number, change its type to int or another numeric data type in the Java class.

Non-static nested classes:
Your nested classes (ThreadRunStepDeltaDetail, MessageCreationStepDetail, ToolCallsStepDetail, and others) are declared without the static modifier. This means they are closely linked to the outer class ThreadRunStepDelta and cannot be instantiated without an instance of the outer class. In the context of JSON deserialization, this can cause problems if the library tries to instantiate these classes directly. Consider declaring all nested classes as static so they can exist independently of an instance of the outer class.

**Comment by sashirestela** [comment]
@Mojo774 First, thanks for using this library. Second, sorry for the delay, I was out of home for some days. Today I'm going to take a look at this issue. Would you mind sharing your request to replicate it?

**Comment by sashirestela** [comment]
@Mojo774 I was able to reproduce the issue, so don't worry about sharing your request.

**Comment by sashirestela** [comment]
@Mojo774 A fix has been provided in the release 2.1.1. You could take a look at the [unit testing](https://github.com/sashirestela/simple-openai/blob/main/src/test/java/io/github/sashirestela/openai/domain/assistant/ThreadDomainTest.java#L260-L340) and [demo](https://github.com/sashirestela/simple-openai/blob/main/src/demo/java/io/github/sashirestela/openai/demo/AssistantServiceDemo.java#L105-L172) to see how to use the streaming functionality

**Comment by sashirestela** [comment]
@Mojo774 I hope you are enjoying this library and if you don't mind, would you like to give us a star ⭐?
